#!/bin/sh

aclocal -I m4 --install                    || exit 1
case `uname` in 
    Darwin*) glibtoolize --install --copy  || exit 1;;
    *) libtoolize --install --copy         || exit 1;;
esac
autoheader                                 || exit 1
autoconf                                   || exit 1
automake --add-missing --copy              || exit 1

exit 0
